---
title: "Week2Day4"
output: html_document
date: "2023-06-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem 2.2

1) 30/34 died in the control group and 45/69 died in the treatment group.
2) 
H0 - The treatment has no effect on the whether a patient dies or not.
HA - THe treatment does have an effect on whether a patient dies or not.

We write alive on 28 cards representing patients who were alive at
the end of the study, and dead on 75 cards representing patients
who were not. Then, we shuffle these cards and split them into two groups:
one group of size 69 representing treatment, and another group of
size 34 representing control. We calculate the difference between
the proportion of dead cards in the treatment and control groups (treatment -
control) and record this value. We repeat this many times to build a distribution
centered at 0.0. Lastly, we calculate the fraction of simulations where
the simulated differences in proportions are greater than .23. If this fraction is low,
we conclude that it is unlikely to have observed such an outcome by chance and
that the null hypothesis should be rejected in favor of the alternative.

3) It is unlikely that the treatment does nothing, so we reject the null hypothesis in favor of the alternative one.

# Problem 2.6

1) 
H0 - The null hypothesis is someone yawning near a person has no effect on whether or not they yawn.
HA - The alternative hypothesis is that someone yawning near you has an effect on whether or not you yawn.

2) The observed difference is ~ 4% (or .04)
3) The p-value for the observed difference is ~ 50%.

