---
title: "Movielens"
date: '`r Sys.time()`'
output:
  html_document:
    #code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
library(scales)
library(tidyverse)
library(knitr)

# set plot theme
theme_set(theme_bw())
```

# Load and preview data

Read data from the `ratings.csv` file
```{r load-data}
ratings <- read_csv('ratings.csv',
                    col_names = c('user_id','movie_id','rating','timestamp'))
```

Loaded `r format(object.size(ratings), units="Mb")` of ratings data, containing `r format(nrow(ratings), big.mark = ",")` ratings. Here's a preview:
```{r preview-data}
head(ratings) %>% kable()
```

# Summary statistics

```{r dist-ratings}
# plot the distribution of rating values https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=26

ratings %>%
  group_by(rating) %>%
  ggplot(aes(x=rating)) +
  geom_histogram(bins = 20) + 
  ylab("Number of Ratings") +
  xlab("Rating") +
  scale_y_continuous(label=comma)
```

## Per-movie stats

```{r aggregate-by-movie}
# aggregate ratings by movie, computing mean rating and number of ratings
# hint: use the n() function for easy counting within a group

ratings %>%
  group_by(movie_id) %>%
  summarize(average_rating=mean(rating), number_of_ratings=n())

```

```{r dist-movie-popularity}
# plot distribution of movie popularity (= number of ratings the movie received)
# hint: try scale_x_log10() for a logarithmic x axis
ratings %>%
  group_by(movie_id) %>%
  summarize(average_rating=mean(rating), number_of_ratings=n()) %>%
  ggplot(aes(x=number_of_ratings)) +
  geom_histogram() +
  scale_x_log10()


```

```{r dist-mean-ratings-by-movie}
# plot distribution of mean ratings by movie https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=28
# hint: try geom_histogram and geom_density

ratings %>%
  group_by(movie_id) %>%
  summarize(average_rating=mean(rating)) %>%
  ggplot(aes(x=average_rating)) +
  geom_histogram()
```

```{r cdf-movie-pop}
# rank movies by popularity (number of ratings) and compute the cdf, or fraction of movies covered by the top-k movies https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=30
# hint: use dplyr's rank and arrange functions, and the base R sum and cumsum functions
# store the result in a new data frame so you can use it in creating figure 2 from the paper below

movies_ranked_by_rating_count <- ratings %>%
  group_by(movie_id) %>%
  summarize(number_of_ratings = n()) %>%
  arrange(desc(number_of_ratings)) %>%
  mutate(rank = row_number())

cdf_movie_popularity <- movies_ranked_by_rating_count %>%
  mutate(cumulative_sum = cumsum(number_of_ratings)) %>%
  mutate(cdf=cumulative_sum/sum(number_of_ratings))
cdf_movie_popularity

# plot the CDF of movie popularity
cdf_movie_popularity %>%
  ggplot(aes(x=rank, y=cdf)) +
  geom_line()

```


# Per-user stats

```{r aggregate-by-user}
# aggregate ratings by user, computing mean and number of ratings

ratings_by_user <- ratings %>%
  group_by(user_id) %>%
  summarize(mean_rating=mean(rating), number_of_ratings=n())
```

```{r dist-user-activity}
# plot distribution of user activity (= number of ratings the user made)
# hint: try a log scale here

ratings_by_user %>%
  ggplot(aes(x=number_of_ratings)) +
  geom_histogram() +
  scale_x_log10()

```

# Anatomy of the long tail

```{r long-tail}
# generate the equivalent of figure 2a of this paper:
# note: don't worry about the "null model" lines
# just do the solid lines and dotted line (optional)
# https://5harad.com/papers/long_tail.pdf
satisfiability_thresholds <- ratings %>%
  group_by(user_id) %>%
  summarize(num_of_ratings_by_user=n()) %>%
  right_join(ratings) %>%
  filter(num_of_ratings_by_user >= 10) %>%
  left_join(movies_ranked_by_rating_count) %>%
  select(user_id, movie_id, rank) %>%
  group_by(user_id) %>%
  summarize(sat_90=quantile(rank, .9), sat_100=quantile(rank, 1.0))
  
sat_90_percent_satsified <- satisfiability_thresholds %>%
  group_by(sat_90) %>%
  count() %>%
  ungroup() %>%
  arrange(sat_90) %>%
  mutate(percent_of_users_satsified=cumsum(n)/sum(n))

sat_100_percent_satsified <- satisfiability_thresholds %>%
  group_by(sat_100) %>%
  count() %>%
  ungroup() %>%
  arrange(sat_100) %>%
  mutate(percent_of_users_satsified=cumsum(n)/sum(n))

sat_90_percent_satsified %>%
  ggplot(aes(x=sat_90, y=percent_of_users_satsified)) +
  geom_line() 
  
  

# Specifically, for the subset of users who rated at least 10 movies,
# produce a plot that shows the fraction of users satisfied (vertical
# axis) as a function of inventory size (horizontal axis). We will
# define "satisfied" as follows: an individual user is satisfied p% of
# the time at inventory of size k if at least p% of the movies they
# rated are contained in the top k most popular movies. As in the
# paper, produce one curve for the 100% user satisfaction level and
# another for 90%---do not, however, bother implementing the null
# model (shown in the dashed lines).
```
